language: rust
rust:
  - nightly

install:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - libedit2
      - g++-multilib
