language: rust
rust:
  - nightly

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
    packages:
      - llvm-3.6
      - llvm-3.6-dev
      - libstdc++
      - libedit2
      - libedit2-dev
      - g++-multilib
      - g++-4.8
before_script:
  - sudo apt-get update
  - sudo apt-get install llvm-3.6
